Optimize CPU I/O processing.
libsidplayfp/libsidplayfp pull request #133
Opened 2024-05-31 10:20 UTC by vitamin-caig

Hello!

This optimization improves I/O for emulated CPU via introducing CPUDataBus abstraction. Previously there were some redundant virtual calls:
 MOS6510::cpuRead -(via c64cpu::cpuRead)-> c64env::cpuRead -(via c64::cpuRead and MMU::cpuRead)-> Bank::peek

Now chain is:
CPUDataBus::cpuRead -(via c64cpubus and MMU::cpuRead)-> Bank::peek

Performance reports (follow-up for #131 ).

98188 tracks rendered on Intel Xeon:
Before: speed=10.45..66.33 avg=29.17 median=29.33
After: speed=9.89..65.49 avg=28.55 median=28.74
Delta: -2.2%/-2.1% (TBH have not idea about degradation reason)

1413 tracks rendered on Ryzen 5 1600:
Before: speed=20.71..44.74 avg=39.14 median=40.03
After: speed=21.82..45.06 avg=40.23 median=41.06
Delta: 2.8%/2.6%

164 tracks rendered on Raspberry Pi 1
Before: speed=1.04..2.07 avg=1.83 median=1.85
After: speed=1.14..2.25 avg=1.96 median=2.00
Delta: 7.1%/8.1%

2024-05-31 22:11 UTC, reFX-Mike commented
For me, this patch slows down songs that use a lot of digis, and speeds up songs that don't use digits a tiny bit (less than 1% faster).

The sub-percentage gain for non-digis is not worth the trade-off.

This is on a "modern" i9-10900.

2024-06-01 14:49 UTC, drfiemost commented
You're right, I can see a slight degradation in i.e. `/MUSICIANS/S/Swallow/Wonderland_XII-Digi_part_1.sid`
I don't see this as a blocker as the majority of tunes don't rely on samples but will keep on hold for further analysis.

2024-06-01 17:00 UTC, reFX-Mike commented
So it seems that for Intel CPUs the speed up is negligible, even slower than before for digits and for AMD and Arm CPUs there is a small speed up.

2024-06-01 20:56 UTC, reFX-Mike commented
So maybe the point could be made to sacrifice some performance for the benefit of the "weaker" CPUs that seem to benefit the most? Sacrificing 1% so the others can get 6-8%?

2024-06-01 21:25 UTC, vitamin-caig commented
A few notes:
- fix should improve playback performance of modules with digital samples since IO optimization exactly
- I have only guesses about degradation on Intel processors:)
- the main goal of all my performance improvements is ARM platform (=almost any android device). They are quite limited in resources and widely spread

2024-06-03 17:06 UTC, drfiemost commented
> * fix should improve playback performance of modules with digital samples since IO optimization exactly

I would expect that too, since digi tunes perform a lot of writes to $D418, but the observed results tell otherwise.
Maybe getting some perf stats could shed some light.

2024-06-15 10:27 UTC, vitamin-caig commented
Hehe, mysterious degradation is uncovered. Binary was built on AMD Ryzen with implicit -march=native, so results vary.

1413 tracks rendered on Intel i7-7700HQ (2.8GHz) with AMD-optimized binary:
Before: speed=24.80..52.54 avg=44.84 median=45.66
After: speed=20.76..49.67 avg=41.41 median=43.32
Delta: -7.6%/-5.2%

Same with Intel-optimized binary:
Before: speed=18.67..50.69 avg=41.11 median=43.06
After: speed=21.06..51.91 avg=44.32 median=44.99
Delta: 7.8%/4.5%

In addition:
164 tracks rendered on Raspberry Pi 3B+ (ARM64 1.4GHz):
Before: speed=2.39..3.40 avg=3.06 median=3.03
After: speed=2.48..3.56 avg=3.18 median=3.15
Delta: 3.9%/4%

2024-06-15 18:30 UTC, reFX-Mike commented
Does the Intel-optimized binary run slower on the Intel CPU than the AMD-optimized binary? I'm referring to the "before" measurements. 45.66 vs. 43.06???

My results are obtained on an Intel i9-10900. Using the same machine to compile and run the tests. Using Clang 18.0.6. No `march` parameter in sight, but might be implicitly using the host arch?

Regardless, the fact that this PR runs faster or Arm is a huge boon, and thus, it should be merged. The majority of all Apple users are on Apple Silicon already, and over the next 4-5 years, the number of Apple Intel users is going to be completely insignificant.

The same could happen on Windows/Linux, as the new Qualcomm Dragon Elite Arm CPUs are coming to market and apparently even beat Apple Silicons' performance levels.

2024-06-15 19:05 UTC, drfiemost requested changes

2024-06-15 19:05 UTC, drfiemost commented on src/c64/CPU/mos6510.h
> +  virtual ~CPUDataBus() {}
this can be marked as default, we're on c++11 now

2024-06-15 19:05 UTC, drfiemost commented on src/c64/mmu.h
> +    uint8_t cpuRead(uint_least16_t addr) { return cpuReadMap[addr >> 12]->peek(addr); }
why remove the const?

2024-06-15 19:06 UTC, drfiemost commented
Can you add back the const on cpuRead and check the performance on a digi tune?

2024-06-16 19:46 UTC, vitamin-caig commented
> check the performance on a digi tune?

Sure. Can you point me some of them?

2024-06-16 19:49 UTC, reFX-Mike commented
/MUSICIANS/M/Mahoney/Kapla_Caves.sid
/MUSICIANS/H/Huelsbeck_Chris/Bad_Cat.sid
/MUSICIANS/H/Huelsbeck_Chris/Great_Giana_Sisters.sid
/MUSICIANS/H/Huelsbeck_Chris/To_be_on_Top.sid
/MUSICIANS/G/Galway_Martin/Arkanoid.sid
/MUSICIANS/G/Galway_Martin/Game_Over.sid
/MUSICIANS/H/Hubbard_Rob/Arcade_Classics.sid
/MUSICIANS/H/Hubbard_Rob/Skate_or_Die_intro.sid
/MUSICIANS/H/Hubbard_Rob/Kings_of_the_Beach_intro.sid
/MUSICIANS/B/Bjerregaard_Johannes/Stormlord.sid

2024-06-18 09:13 UTC, vitamin-caig commented
92 tracks in 10 files. Report also contains result for #131 changes for the sake of history:

Binary built and run on Ryzen 5 1600:
- Vanilla libsidplayfp: speed=22.09..39.86 avg=32.10 median=33.67
- Only CPU instructions optimized: speed=23.14..42.19 avg=37.37 median=39.76
- Also CPU events optimized: speed=22.94..43.23 avg=37.06 median=39.66
- Optimized I/O: speed=21.87..42.38 avg=37.41 median=39.74

Delta for the last two cases: 0.9%/0.2%

Raspberry Pi 3B+ (arm64v8):
- Vanilla libsidplayfp: speed=2.32..3.30 avg=2.86 median=2.88
- Only CPU instructions optimized: speed=2.39..3.92 avg=3.00 median=3.00
- Also CPU events optimized: speed=2.73..3.26 avg=3.06 median=3.13
- Optimized I/O: speed=2.55..4.01 avg=3.20 median=3.22

Delta for the last two cases: 4.6%/2.9%

Raspberry Pi (armv6):
- Vanilla libsidplayfp: speed=1.25..2.07 avg=1.77 median=1.89
- Only CPU instructions optimized: speed=1.12..2.13 avg=1.84 median=1.97
- Also CPU events optimized: speed=1.27..2.18 avg=1.83 median=1.94
- Optimized I/O: speed=1.26..2.14 avg=1.89 median=2.00

Delta for the last two cases: 3.3%/3.1%

Binary build on Ryzen 5 and run on Intel:
- Vanilla libsidplayfp: speed=23.64..45.07 avg=38.81 median=40.94
- Only CPU instructions optimized: speed=24.13..48.91 avg=40.93 median=42.88
- Also CPU events optimized: speed=25.24..48.97 avg=41.53 median=43.63
- Optimized I/O: speed=25.54..49.84 avg=41.93 median=44.22

Delta for the last two cases: 1%/1.4%

Binary build and run on Intel:
- Also CPU events optimized: speed=23.65..49.59 avg=40.13 median=42.67
- Optimized I/O: speed=24.33..48.98 avg=41.22 median=43.72

Delta: 2.7%/2.5%

Looks like compiler difference (both gcc, but at Intel OS it may be a bit more recent) also makes sense and gives various performance boosts on different steps.

2024-06-18 16:46 UTC, reFX-Mike commented
It’s not clear to me, when you refer to “old fork”, do you mean without the const? Could you clarify your comment, please?

2024-06-18 17:19 UTC, vitamin-caig commented
> It’s not clear to me, when you refer to “old fork”, do you mean without the const? Could you clarify your comment, please?

Long time ago I used libsidplayfp version 1.6.2 in my project. There were a lot of performance-related changes (some of them are already in upstream) - that version I call oldfork.
Now I have to update used version of libsidplayfp. To make world better and to avoid performance and merge problems I decided to backport some performance-related fixes.

2024-06-18 20:44 UTC, reFX-Mike commented
I think @drfiemost wanted to know if the const addition/removal made a difference, not a comparison to your older fork.

2024-06-18 21:57 UTC, vitamin-caig commented
> I think @drfiemost wanted to know if the const addition/removal made a difference, not a comparison to your older fork.

I haven't noticed any significant difference

2024-06-20 18:12 UTC, reFX-Mike commented
For me, /MUSICIANS/M/Mahoney/Kapla_Caves.sid is actually a bit faster than before. Not much (12.79 vs 13.23), but absolutely worthwhile. Maybe 

I don't know if the const makes any difference, but this patch is worthwhile overall. I've merged it into my fork.

Can't explain why it's suddenly faster compared to my tests three weeks ago. Maybe a new Clang version? I've added `const` to all cpuRead functions, so maybe that sped it up?

2024-06-30 17:03 UTC, drfiemost approved these changes

2024-06-30 17:04 UTC, drfiemost commented
I still see a degradation in Wonderland_XII, but I don't have the time to delve deeper now.

2024-06-30 17:04 UTC, merged